---
- name: copy alertmanager config
  template:
    force: true
    src: "{{ alertmanager_config_file }}"
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: 0644
    validate: "{{ alertmanager_release_dir }}/amtool --alertmanager.url=  check-config %s"
  notify:
    - restart alertmanager
